apiVersion: v1
kind: ServiceAccount
metadata:
  name:  controller-sa
  namespace: controller-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller-sa-admin-binding
subjects:
- kind: ServiceAccount
  name: controller-sa
  namespace: controller-admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  controller-node
  namespace: controller-admin
  labels:
    name:  controller-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: controller-node-pod
  template:
    metadata:
      labels:
        app: controller-node-pod
    spec:
      serviceAccount: controller-sa
      volumes:
      - name: shared-config
        emptyDir: {}
      containers:
      - image:  payaljain/k8s-leader-election-node:v1.10
        name:  controller-node-pod
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort:  8080
        volumeMounts:
        - mountPath: /config
          name: shared-config
---
